# Copyright 2024 The HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Records a dataset. Actions for the robot can be either generated by teleoperation or by a policy.

Example:

```shell
python -m lerobot.record \
    --robot.type=so100_follower \
    --robot.port=/dev/tty.usbmodem58760431541 \
    --robot.cameras="{laptop: {type: opencv, camera_index: 0, width: 640, height: 480}}" \
    --robot.id=black \
    --teleop.type=so100_leader \
    --teleop.port=/dev/tty.usbmodem58760431551 \
    --teleop.id=blue \
    --dataset.repo_id=aliberts/record-test \
    --dataset.num_episodes=2 \
    --dataset.single_task="Grab the cube"
```
"""

import logging
import time
from dataclasses import asdict, dataclass
from pathlib import Path
from pprint import pformat
import multiprocessing as mp
from typing import Tuple
import torch, time, logging

from lerobot.common.cameras import (  # noqa: F401
    CameraConfig,  # noqa: F401
)
from lerobot.common.cameras.opencv.configuration_opencv import OpenCVCameraConfig  # noqa: F401
from lerobot.common.cameras.realsense.configuration_realsense import RealSenseCameraConfig  # noqa: F401
from lerobot.common.datasets.lerobot_dataset import LeRobotDataset
from lerobot.common.datasets.utils import build_dataset_frame, hw_to_dataset_features
from lerobot.common.policies.factory import make_policy
from lerobot.common.policies.act.configuration_act import ACTConfig
from lerobot.common.robots import (  # noqa: F401
    Robot,
    RobotConfig,
    koch_follower,
    aloha_agilex_follower,
    make_robot_from_config,
    so100_follower,
    so101_follower,
)
from lerobot.common.teleoperators import (  # noqa: F401
    Teleoperator,
    TeleoperatorConfig,
    make_teleoperator_from_config,
)
from lerobot.common.utils.control_utils import (
    init_keyboard_listener,
    is_headless,
    predict_action,
    sanity_check_dataset_name,
    sanity_check_dataset_robot_compatibility,
)
from lerobot.common.utils.robot_utils import busy_wait
from lerobot.common.utils.utils import (
    get_safe_torch_device,
    init_logging,
    log_say,
)
from lerobot.common.utils.visualization_utils import _init_rerun
from lerobot.configs import parser
from lerobot.configs.policies import PreTrainedConfig

from .common.teleoperators import koch_leader, so100_leader, so101_leader, aloha_agilex_leader  # noqa: F401


@dataclass
class DatasetRecordConfig:
    # Dataset identifier. By convention it should match '{hf_username}/{dataset_name}' (e.g. `lerobot/test`).
    repo_id: str
    # A short but accurate description of the task performed during the recording (e.g. "Pick the Lego block and drop it in the box on the right.")
    single_task: str
    # Root directory where the dataset will be stored (e.g. 'dataset/path').
    root: str | Path | None = None
    # Limit the frames per second.
    fps: int = 30
    # Number of seconds for data recording for each episode.
    episode_time_s: int | float = 6
    # Number of seconds for resetting the environment after each episode.
    reset_time_s: int | float = 1
    # Number of episodes to record.
    num_episodes: int = 50
    # Encode frames in the dataset into video
    video: bool = True
    # Upload dataset to Hugging Face hub.
    push_to_hub: bool = False
    # Upload on private repository on the Hugging Face hub.
    private: bool = False
    # Add tags to your dataset on the hub.
    tags: list[str] | None = None
    # Number of subprocesses handling the saving of frames as PNG. Set to 0 to use threads only;
    # set to ≥1 to use subprocesses, each using threads to write images. The best number of processes
    # and threads depends on your system. We recommend 4 threads per camera with 0 processes.
    # If fps is unstable, adjust the thread count. If still unstable, try using 1 or more subprocesses.
    num_image_writer_processes: int = 0
    # Number of threads writing the frames as png images on disk, per camera.
    # Too many threads might cause unstable teleoperation fps due to main thread being blocked.
    # Not enough threads might cause low camera fps.
    num_image_writer_threads_per_camera: int = 4

    def __post_init__(self):
        if self.single_task is None:
            raise ValueError("You need to provide a task as argument in `single_task`.")


@dataclass
class DeployConfig:
    robot1: RobotConfig
    dataset: DatasetRecordConfig
    policy: PreTrainedConfig

    def __post_init__(self):
        # HACK: We parse again the cli args here to get the pretrained path if there was one.
        policy_path = parser.get_path_arg("policy")
        if policy_path:
            cli_overrides = parser.get_cli_overrides("policy")
            self.policy = PreTrainedConfig.from_pretrained(policy_path, cli_overrides=cli_overrides)
            self.policy.pretrained_path = policy_path

    @classmethod
    def __get_path_fields__(cls) -> list[str]:
        """This enables the parser to load config from the policy using `--policy.path=local/dir`"""
        return ["policy"]

# ---------- 子进程：推理循环 ----------
def inference_worker(
    in_q: mp.Queue,
    out_q: mp.Queue,
    cfg_policy,
    ds_meta
):
    """
    独立进程：收到 observation_frame → 预测 → 输出 action_values
    """
    # 1. 只在该进程里加载一次模型 / CUDA
    policy = make_policy(cfg_policy, ds_meta=ds_meta) if cfg_policy else None
    device = get_safe_torch_device(policy.config.device)
    use_amp = policy.config.use_amp

    while True:
        item = in_q.get()
        if item is None:            # 收到结束标识
            break
        idx, obs_frame = item       # idx 用来对应主进程里的顺序
        action_vals = predict_action(obs_frame, policy, device, use_amp)
        out_q.put((idx, action_vals))

@parser.wrap()
def deploy(cfg: DeployConfig):
    init_logging()
    logging.info(pformat(asdict(cfg)))


    robot1 = make_robot_from_config(cfg.robot1)
    merged_action_features = {**robot1.action_features}
    merged_observation_features = {**robot1.observation_features}
    action_features = hw_to_dataset_features(merged_action_features, "action", cfg.dataset.video)
    obs_features = hw_to_dataset_features(merged_observation_features, "observation", cfg.dataset.video)

    dataset = LeRobotDataset(
        cfg.dataset.repo_id,
        root=cfg.dataset.root,
    )

    print(cfg.policy.type)
    print(cfg.policy.pretrained_path)
    # Load pretrained policy
    # policy = None if cfg.policy is None else make_policy(cfg.policy, ds_meta=dataset.meta)

    # ==== 1. 启动推理子进程 ====
    ctx = mp.get_context("spawn")        # "spawn" 更安全，尤其 CUDA
    in_q: mp.Queue = ctx.Queue(maxsize=4)   # 根据实时性调节 maxsize
    out_q: mp.Queue = ctx.Queue(maxsize=4)

    proc = ctx.Process(
        target=inference_worker,
        args=(in_q, out_q, cfg.policy, dataset.meta)
    )
    proc.daemon = True
    proc.start()

    robot1.connect()
    i, sent_idx, recv_idx = 0, 0, 0
    kMaxTimeStamps = 6000

    # rows = []
    step = 1
    step_time = step/(dataset.fps-2)

    while i < kMaxTimeStamps:
        t0 = time.perf_counter()

        # 2.1 采集
        observation = robot1.get_observation()
        obs_frame = build_dataset_frame(
            obs_features, observation, prefix="observation"
        )

        # 2.2 将帧放入队列（若满可选择丢帧 or 阻塞）
        try:
            in_q.put_nowait((sent_idx, obs_frame))
            sent_idx += 1
        except mp.queues.Full:
            logging.warning("inference queue full, dropping frame")
            # 丢帧或阻塞: in_q.put((sent_idx, obs_frame))

        # 不用 try/except；直接检查队列是否为空
        action_vals = None
        while not out_q.empty():
            idx, action_vals = out_q.get_nowait()
            recv_idx = idx
            logging.debug(f"got result #{recv_idx}")

        # 2.4 如果有最新动作，就发给机器人
        if action_vals is not None:
            # logging.info(recv_idx)
            robot1.send_action_np(action_vals[:7])

        # 2.5 统计
        i += 1
        dt_s = time.perf_counter() - t0
        time.sleep(max(step_time - dt_s,0))
        # logging.info(f"loop {i} dt={t1-t0:.3f} s")

    # ==== 3. 结束 ====
    in_q.put(None)      # 通知子进程退出
    proc.join()
    robot1.disconnect()

if __name__ == "__main__":
    logging.info("Running inference (main process loop)")
    deploy()
